import type { Challenge, PublicChallenge } from "./ai/types";

type ChallengeSeed = readonly [
  id: string,
  englishPrompt: string,
  exampleMandarinAnswer: string,
  category: string,
  targetConcepts: readonly string[],
  notes?: string,
];

const challengeSeeds: readonly ChallengeSeed[] = [
  ["beginner-001-greet-neighbor", "Hello, how have you been recently?", "你好，你最近怎么样？", "greetings", ["你好", "最近", "怎么样"]],
  ["beginner-002-introduce-name", "Hello, my name is Kevin.", "你好，我叫Kevin。", "greetings", ["我叫", "name introduction"]],
  ["beginner-003-meet-pleasure", "Nice to meet you.", "很高兴认识你。", "greetings", ["很高兴", "认识你"]],
  ["beginner-004-say-goodbye", "Goodbye, see you tomorrow.", "再见，明天见。", "greetings", ["再见", "明天见"]],
  ["beginner-005-thank-help", "Thank you for helping me.", "谢谢你帮我。", "greetings", ["谢谢", "帮我"]],
  ["beginner-006-apologize-late", "Sorry, I am late.", "对不起，我迟到了。", "greetings", ["对不起", "迟到了"]],
  ["beginner-007-ask-surname", "Excuse me, what is your last name?", "请问，您贵姓？", "greetings", ["请问", "您", "贵姓"]],
  ["beginner-008-say-long-time", "Long time no see.", "好久不见。", "greetings", ["好久不见"]],
  ["beginner-009-ask-country", "What country are you from?", "你是哪国人？", "greetings", ["哪国人", "是"]],
  ["beginner-010-answer-country", "I am American.", "我是美国人。", "greetings", ["我是", "美国人"]],
  ["beginner-011-order-coffee", "I would like one cup of hot coffee.", "我要一杯热咖啡。", "food ordering", ["我要", "一杯", "热咖啡"]],
  ["beginner-012-order-no-spicy", "Please do not make it spicy.", "请不要放辣。", "food ordering", ["请不要", "放辣"]],
  ["beginner-013-ask-menu", "Do you have an English menu?", "你们有英文菜单吗？", "food ordering", ["有", "英文菜单", "吗"]],
  ["beginner-014-water", "Please give me a glass of water.", "请给我一杯水。", "food ordering", ["请给我", "一杯水"]],
  ["beginner-015-check-please", "The bill, please.", "请买单。", "food ordering", ["买单", "请"]],
  ["beginner-016-vegetarian", "I do not eat meat.", "我不吃肉。", "food ordering", ["不吃", "肉"]],
  ["beginner-017-takeout", "I would like this to go.", "我要打包。", "food ordering", ["我要", "打包"]],
  ["beginner-018-allergy", "I am allergic to peanuts.", "我对花生过敏。", "food ordering", ["对...过敏", "花生"]],
  ["beginner-019-tastes-good", "This dish is very delicious.", "这个菜很好吃。", "food ordering", ["这个菜", "很好吃"]],
  ["beginner-020-more-rice", "Please give me one more bowl of rice.", "请再给我一碗米饭。", "food ordering", ["再", "一碗", "米饭"]],
  ["beginner-021-ask-price", "How much is this?", "这个多少钱？", "shopping", ["这个", "多少钱"]],
  ["beginner-022-too-expensive", "It is too expensive.", "太贵了。", "shopping", ["太...了", "贵"]],
  ["beginner-023-smaller-size", "Do you have a smaller size?", "有小一点的吗？", "shopping", ["有...吗", "小一点"]],
  ["beginner-024-try-on", "Can I try this on?", "我可以试一下吗？", "shopping", ["可以", "试一下", "吗"]],
  ["beginner-025-pay-card", "Can I pay by card?", "可以刷卡吗？", "shopping", ["可以", "刷卡", "吗"]],
  ["beginner-026-buy-this", "I want to buy this one.", "我要买这个。", "shopping", ["要买", "这个"]],
  ["beginner-027-just-looking", "I am just looking.", "我只是看看。", "shopping", ["只是", "看看"]],
  ["beginner-028-receipt", "Please give me a receipt.", "请给我发票。", "shopping", ["请给我", "发票"]],
  ["beginner-029-different-color", "Do you have another color?", "有别的颜色吗？", "shopping", ["别的", "颜色", "吗"]],
  ["beginner-030-discount", "Can it be a little cheaper?", "可以便宜一点吗？", "shopping", ["可以", "便宜一点", "吗"]],
  ["beginner-031-where-bathroom", "Where is the restroom?", "洗手间在哪里？", "directions", ["在哪里", "洗手间"]],
  ["beginner-032-go-straight", "Go straight ahead.", "一直往前走。", "directions", ["一直", "往前走"]],
  ["beginner-033-turn-left", "Turn left at the intersection.", "在路口左转。", "directions", ["路口", "左转"]],
  ["beginner-034-near-hotel", "Is the hotel nearby?", "酒店在附近吗？", "directions", ["酒店", "附近", "吗"]],
  ["beginner-035-far", "Is it far from here?", "离这里远吗？", "directions", ["离", "这里", "远吗"]],
  ["beginner-036-lost", "I am lost.", "我迷路了。", "directions", ["迷路了"]],
  ["beginner-037-map", "Please show me on the map.", "请在地图上给我看。", "directions", ["地图上", "给我看"]],
  ["beginner-038-next-to-bank", "The cafe is next to the bank.", "咖啡馆在银行旁边。", "directions", ["在...旁边", "银行"]],
  ["beginner-039-opposite", "The supermarket is across from the park.", "超市在公园对面。", "directions", ["在...对面", "公园"]],
  ["beginner-040-subway-entrance", "Where is the subway entrance?", "地铁口在哪里？", "directions", ["地铁口", "在哪里"]],
  ["beginner-041-taxi-airport", "I want to go to the airport.", "我要去机场。", "transportation", ["要去", "机场"]],
  ["beginner-042-bus-stop", "Where is the bus stop?", "公交车站在哪里？", "transportation", ["公交车站", "在哪里"]],
  ["beginner-043-which-line", "Which subway line goes to the train station?", "哪条地铁线到火车站？", "transportation", ["哪条", "地铁线", "到"]],
  ["beginner-044-buy-ticket", "I want to buy one ticket.", "我要买一张票。", "transportation", ["买", "一张票"]],
  ["beginner-045-arrival-time", "What time does the train arrive?", "火车几点到？", "transportation", ["几点", "到"]],
  ["beginner-046-missed-bus", "I missed the bus.", "我错过了公交车。", "transportation", ["错过了", "公交车"]],
  ["beginner-047-get-off-here", "Should I get off here?", "我在这里下车吗？", "transportation", ["在这里", "下车", "吗"]],
  ["beginner-048-too-far-walk", "It is too far to walk.", "走路太远了。", "transportation", ["走路", "太远了"]],
  ["beginner-049-taxi-cost", "About how much does a taxi cost?", "打车大概多少钱？", "transportation", ["打车", "大概", "多少钱"]],
  ["beginner-050-ride-share", "I already called a car.", "我已经叫车了。", "transportation", ["已经", "叫车了"]],
  ["beginner-051-meet-tomorrow", "Are you free tomorrow?", "你明天有空吗？", "scheduling", ["明天", "有空", "吗"]],
  ["beginner-052-meet-time", "Let's meet at three o'clock.", "我们三点见吧。", "scheduling", ["三点", "见吧"]],
  ["beginner-053-cancel-plan", "I need to cancel today's plan.", "我今天要取消计划。", "scheduling", ["今天", "取消计划"]],
  ["beginner-054-reschedule", "Can we change the appointment to Friday?", "可以改到星期五吗？", "scheduling", ["改到", "星期五", "吗"]],
  ["beginner-055-busy-now", "I am busy right now.", "我现在很忙。", "scheduling", ["现在", "很忙"]],
  ["beginner-056-after-work", "I can go after work.", "我下班以后可以去。", "scheduling", ["下班以后", "可以去"]],
  ["beginner-057-weekend-plan", "What are you doing this weekend?", "你这个周末做什么？", "scheduling", ["这个周末", "做什么"]],
  ["beginner-058-late-five", "I will be five minutes late.", "我会晚五分钟。", "scheduling", ["会", "晚", "五分钟"]],
  ["beginner-059-call-tonight", "Can I call you tonight?", "我今晚可以给你打电话吗？", "scheduling", ["今晚", "打电话", "吗"]],
  ["beginner-060-no-time", "I do not have time today.", "我今天没有时间。", "scheduling", ["没有时间", "今天"]],
  ["beginner-061-study-chinese", "I am studying Chinese.", "我在学中文。", "work/school", ["在", "学中文"]],
  ["beginner-062-work-office", "I work in an office.", "我在办公室工作。", "work/school", ["在", "办公室", "工作"]],
  ["beginner-063-have-meeting", "I have a meeting this afternoon.", "我今天下午有会议。", "work/school", ["今天下午", "有会议"]],
  ["beginner-064-homework", "I need to do homework.", "我要做作业。", "work/school", ["要", "做作业"]],
  ["beginner-065-ask-question", "Teacher, I have a question.", "老师，我有一个问题。", "work/school", ["老师", "有一个问题"]],
  ["beginner-066-dont-understand", "I do not understand.", "我不明白。", "work/school", ["不明白"]],
  ["beginner-067-repeat-please", "Please say it again.", "请再说一遍。", "work/school", ["请", "再", "一遍"]],
  ["beginner-068-speak-slowly", "Please speak a little more slowly.", "请说慢一点。", "work/school", ["请", "慢一点"]],
  ["beginner-069-finish-work", "I finished my work.", "我做完工作了。", "work/school", ["做完", "了"]],
  ["beginner-070-email", "I will send an email.", "我会发邮件。", "work/school", ["会", "发邮件"]],
  ["beginner-071-not-feel-well", "I do not feel well.", "我不舒服。", "health", ["不舒服"]],
  ["beginner-072-headache", "I have a headache.", "我头疼。", "health", ["头疼"]],
  ["beginner-073-doctor", "I need to see a doctor.", "我要看医生。", "health", ["要", "看医生"]],
  ["beginner-074-medicine", "Where can I buy medicine?", "哪里可以买药？", "health", ["哪里", "可以买药"]],
  ["beginner-075-fever", "I have a fever.", "我发烧了。", "health", ["发烧了"]],
  ["beginner-076-cold", "I caught a cold.", "我感冒了。", "health", ["感冒了"]],
  ["beginner-077-water-please", "My throat hurts; please give me some water.", "我嗓子疼，请给我一点水。", "health", ["嗓子疼", "一点水"]],
  ["beginner-078-rest", "I need to rest today.", "我今天需要休息。", "health", ["需要", "休息"]],
  ["beginner-079-hospital", "Where is the hospital?", "医院在哪里？", "health", ["医院", "在哪里"]],
  ["beginner-080-better-now", "I feel much better now.", "我现在好多了。", "health", ["现在", "好多了"]],
  ["beginner-081-home-address", "My home is near the subway station.", "我家在地铁站附近。", "home", ["我家", "附近"]],
  ["beginner-082-room-small", "My room is a little small.", "我的房间有点小。", "home", ["房间", "有点", "小"]],
  ["beginner-083-clean-house", "I need to clean the house.", "我要打扫房子。", "home", ["要", "打扫房子"]],
  ["beginner-084-wifi", "What is the Wi-Fi password?", "无线网密码是什么？", "home", ["无线网", "密码", "是什么"]],
  ["beginner-085-lights", "Please turn off the light.", "请关灯。", "home", ["请", "关灯"]],
  ["beginner-086-too-noisy", "It is too noisy here.", "这里太吵了。", "home", ["这里", "太吵了"]],
  ["beginner-087-key", "I forgot to bring my key.", "我忘了带钥匙。", "home", ["忘了", "带钥匙"]],
  ["beginner-088-cook-dinner", "I am cooking dinner at home.", "我在家做晚饭。", "home", ["在家", "做晚饭"]],
  ["beginner-089-laundry", "I need to wash clothes.", "我要洗衣服。", "home", ["要", "洗衣服"]],
  ["beginner-090-live-alone", "I live alone.", "我一个人住。", "home", ["一个人", "住"]],
  ["beginner-091-like-tea", "I like drinking tea.", "我喜欢喝茶。", "preferences", ["喜欢", "喝茶"]],
  ["beginner-092-dislike-coffee", "I do not like coffee.", "我不喜欢咖啡。", "preferences", ["不喜欢", "咖啡"]],
  ["beginner-093-prefer-noodles", "I prefer noodles.", "我比较喜欢面条。", "preferences", ["比较喜欢", "面条"]],
  ["beginner-094-favorite-color", "My favorite color is blue.", "我最喜欢的颜色是蓝色。", "preferences", ["最喜欢", "颜色", "蓝色"]],
  ["beginner-095-like-running", "I like running in the morning.", "我喜欢早上跑步。", "preferences", ["喜欢", "早上", "跑步"]],
  ["beginner-096-weather-hot", "The weather is very hot today.", "今天天气很热。", "small talk", ["今天天气", "很热"]],
  ["beginner-097-raining", "It is raining outside.", "外面在下雨。", "small talk", ["外面", "在下雨"]],
  ["beginner-098-weekend-good", "Was your weekend good?", "你周末过得好吗？", "small talk", ["周末", "过得好吗"]],
  ["beginner-099-tired-today", "I am a little tired today.", "我今天有点累。", "small talk", ["今天", "有点累"]],
  ["beginner-100-movie-good", "This movie is very good.", "这部电影很好看。", "small talk", ["这部电影", "很好看"]],
];

export const challenges: Challenge[] = challengeSeeds.map(
  ([id, englishPrompt, exampleMandarinAnswer, category, targetConcepts, notes]) => ({
    id,
    englishPrompt,
    exampleMandarinAnswer,
    category,
    difficulty: "beginner",
    targetConcepts: [...targetConcepts],
    ...(notes ? { notes } : {}),
  }),
);

export function getRandomChallenge(): Challenge {
  return challenges[Math.floor(Math.random() * challenges.length)];
}

export function getChallengeById(id: string): Challenge | undefined {
  return challenges.find((challenge) => challenge.id === id);
}

export function toPublicChallenge(challenge: Challenge): PublicChallenge {
  return {
    id: challenge.id,
    englishPrompt: challenge.englishPrompt,
    category: challenge.category,
    difficulty: challenge.difficulty,
    targetConcepts: challenge.targetConcepts,
    ...(challenge.notes ? { notes: challenge.notes } : {}),
  };
}
